/**
 * Mock implementation of the actual SharePoint environment for testing purposes.
 *
 * DO NOT EXPOSE CUSTOM PROPERTIES FROM CLIENT INSTANCE
 * --
 *
 */
var _spPageContextInfo = {
  webAbsoluteUrl: `${location.origin}/site`,
  webTitle: `SPARC.js`,
  formDigestValue: '0x1234MOCK_DIGEST_VALUE_FOR_SANDBOX',
  formDigestTimeoutSeconds: 1800,
  userLoginName: 'i:0#.w|SANDBOX\\john.doe',
};

/**
 * Management Platform seed data -- merged into SPInterceptor.store at startup.
 * Projects, Programs, ProjectUpdates, Proposals from .claude/rules/seed-data.md.
 * Schemas from .claude/rules/sharepoint-schemas.md.
 *
 * User fields follow UserIdentity format per ERD:
 *   UI  (single):  JSON string '{"email":"...","displayName":"..."}'
 *   UI[] (array):  JSON string '[{"email":"...","displayName":"..."},...]'
 *   *Email (IDX):  plain email string for CAML queries
 */

// -- UserIdentity helpers for seed data readability --
function _ui(email, name) { return JSON.stringify({ email: email, displayName: name }); }
function _uiArr(pairs) { return JSON.stringify(pairs.map(function (p) { return { email: p[0], displayName: p[1] }; })); }

// People registry
var _P = {
  johnDoe:      ['john.doe@example.com',      'John Doe'],
  janeSmith:    ['jane.smith@example.com',     'Jane Smith'],
  mariaGarcia:  ['maria.garcia@example.com',   'Maria Garcia'],
  sarahWilliams:['sarah.williams@example.com', 'Sarah Williams'],
  aliceWong:    ['alice.wong@example.com',      'Alice Wong'],
  carlosDiaz:   ['carlos.diaz@example.com',     'Carlos Diaz'],
  bobJones:     ['bob.jones@example.com',       'Bob Jones'],
  alexMartin:   ['alex.martin@example.com',     'Alex Martin'],
  jenniferLee:  ['jennifer.lee@example.com',    'Jennifer Lee'],
  mikeBrown:    ['mike.brown@example.com',      'Mike Brown'],
  davidPark:    ['david.park@example.com',      'David Park'],
  emmaWhite:    ['emma.white@example.com',      'Emma White'],
};

var _spMockData = {
  // Current user's groups (john.doe is a ProjectManager and Admin)
  groups: [
    { Id: 20, Title: 'ProjectManagers', Description: 'Project management access', OwnerTitle: 'Admin' },
    { Id: 30, Title: 'Admins', Description: 'Full administrative access', OwnerTitle: 'Admin' },
  ],

  // Group membership for getGroupUsers() handler
  groupMembers: {
    10: [ // Collaborators
      { Id: 7, LoginName: 'i:0#.w|SANDBOX\\bjones', Title: _P.bobJones[1], Email: _P.bobJones[0] },
      { Id: 8, LoginName: 'i:0#.w|SANDBOX\\amartin', Title: _P.alexMartin[1], Email: _P.alexMartin[0] },
      { Id: 9, LoginName: 'i:0#.w|SANDBOX\\jlee', Title: _P.jenniferLee[1], Email: _P.jenniferLee[0] },
      { Id: 10, LoginName: 'i:0#.w|SANDBOX\\mbrown', Title: _P.mikeBrown[1], Email: _P.mikeBrown[0] },
      { Id: 11, LoginName: 'i:0#.w|SANDBOX\\dpark', Title: _P.davidPark[1], Email: _P.davidPark[0] },
      { Id: 12, LoginName: 'i:0#.w|SANDBOX\\ewhite', Title: _P.emmaWhite[1], Email: _P.emmaWhite[0] },
    ],
    20: [ // ProjectManagers
      { Id: 1, LoginName: 'i:0#.w|SANDBOX\\john.doe', Title: _P.johnDoe[1], Email: _P.johnDoe[0] },
      { Id: 2, LoginName: 'i:0#.w|SANDBOX\\jsmith', Title: _P.janeSmith[1], Email: _P.janeSmith[0] },
      { Id: 3, LoginName: 'i:0#.w|SANDBOX\\mgarcia', Title: _P.mariaGarcia[1], Email: _P.mariaGarcia[0] },
      { Id: 4, LoginName: 'i:0#.w|SANDBOX\\swilliams', Title: _P.sarahWilliams[1], Email: _P.sarahWilliams[0] },
      { Id: 5, LoginName: 'i:0#.w|SANDBOX\\awong', Title: _P.aliceWong[1], Email: _P.aliceWong[0] },
      { Id: 6, LoginName: 'i:0#.w|SANDBOX\\cdiaz', Title: _P.carlosDiaz[1], Email: _P.carlosDiaz[0] },
    ],
    30: [ // Admins
      { Id: 1, LoginName: 'i:0#.w|SANDBOX\\john.doe', Title: _P.johnDoe[1], Email: _P.johnDoe[0] },
    ],
  },

  lists: {
    Projects: {
      nextId: 16,
      fields: [
        { Title: 'Title', InternalName: 'Title', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: true },
        { Title: 'UUID', InternalName: 'UUID', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: true },
        { Title: 'UmbrellaProgram', InternalName: 'UmbrellaProgram', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: false },
        { Title: 'LinkedPrograms', InternalName: 'LinkedPrograms', TypeAsString: 'Note', FieldTypeKind: 3, Indexed: false },
        { Title: 'Context', InternalName: 'Context', TypeAsString: 'Note', FieldTypeKind: 3, Indexed: false },
        { Title: 'Objectives', InternalName: 'Objectives', TypeAsString: 'Note', FieldTypeKind: 3, Indexed: false },
        { Title: 'Scope', InternalName: 'Scope', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: false },
        { Title: 'ProjectType', InternalName: 'ProjectType', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: true },
        { Title: 'TechProject', InternalName: 'TechProject', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: false },
        { Title: 'TechPhase', InternalName: 'TechPhase', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: false },
        { Title: 'StartDate', InternalName: 'StartDate', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: false },
        { Title: 'ExpectedEndDate', InternalName: 'ExpectedEndDate', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: false },
        { Title: 'GDPRClassification', InternalName: 'GDPRClassification', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: false },
        { Title: 'BusinessLine', InternalName: 'BusinessLine', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: false },
        { Title: 'Product', InternalName: 'Product', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: false },
        { Title: 'Sponsor', InternalName: 'Sponsor', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: false },
        { Title: 'Stakeholders', InternalName: 'Stakeholders', TypeAsString: 'Note', FieldTypeKind: 3, Indexed: false },
        { Title: 'PMMembers', InternalName: 'PMMembers', TypeAsString: 'Note', FieldTypeKind: 3, Indexed: false },
        { Title: 'PMMembersEmail', InternalName: 'PMMembersEmail', TypeAsString: 'Note', FieldTypeKind: 3, Indexed: false },
        { Title: 'Status', InternalName: 'Status', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: true },
        { Title: 'ProjectManager', InternalName: 'ProjectManager', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: false },
        { Title: 'ProjectManagerEmail', InternalName: 'ProjectManagerEmail', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: true },
        { Title: 'Role', InternalName: 'Role', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: false },
        { Title: 'TargetType', InternalName: 'TargetType', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: false },
        { Title: 'TargetValue', InternalName: 'TargetValue', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: false },
        { Title: 'TargetValueType', InternalName: 'TargetValueType', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: false },
        { Title: 'TargetScope', InternalName: 'TargetScope', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: false },
        { Title: 'AchievedValue', InternalName: 'AchievedValue', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: false },
        { Title: 'AchievedDate', InternalName: 'AchievedDate', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: false },
        { Title: 'Validated', InternalName: 'Validated', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: false },
        { Title: 'NpsScore', InternalName: 'NpsScore', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: false },
        { Title: 'ClientFeedback', InternalName: 'ClientFeedback', TypeAsString: 'Note', FieldTypeKind: 3, Indexed: false },
        { Title: 'Improvements', InternalName: 'Improvements', TypeAsString: 'Note', FieldTypeKind: 3, Indexed: false },
        { Title: 'AccessLevel', InternalName: 'AccessLevel', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: true },
        { Title: 'SubmittedBy', InternalName: 'SubmittedBy', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: false },
        { Title: 'SubmittedByEmail', InternalName: 'SubmittedByEmail', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: true },
      ],
      items: [
        {
          Id: 1,
          Title: 'IB4F - IB Portal ECM',
          UUID: 'uuid-proj-001',
          UmbrellaProgram: 'Digital Transformation',
          LinkedPrograms: 'uuid-prog-001',
          Context: 'Enterprise content management portal for the investment banking front office. Consolidates document workflows across multiple legacy systems.',
          Objectives: 'Reduce document processing time by 40% and eliminate manual handoffs between teams.',
          Scope: 'In Scope',
          ProjectType: 'Tech',
          TechProject: 'SharePoint',
          TechPhase: 'Dev',
          StartDate: '2025-09-15',
          ExpectedEndDate: '2026-06-30',
          GDPRClassification: 'Contact Information (CPD)',
          BusinessLine: 'CCG',
          Product: 'IB Portal',
          Sponsor: _ui(_P.mariaGarcia[0], _P.mariaGarcia[1]),
          Stakeholders: _uiArr([_P.bobJones, _P.alexMartin]),
          PMMembers: _uiArr([_P.johnDoe, _P.sarahWilliams]),
          PMMembersEmail: 'john.doe@example.com;sarah.williams@example.com',
          Status: 'In Progress',
          ProjectManager: _ui(_P.janeSmith[0], _P.janeSmith[1]),
          ProjectManagerEmail: 'jane.smith@example.com',
          Role: 'Leading',
          TargetType: 'User Experience',
          TargetValue: '500000',
          TargetValueType: 'EUR',
          TargetScope: 'EMEA',
          AchievedValue: '',
          AchievedDate: '',
          Validated: 'false',
          NpsScore: '',
          ClientFeedback: '',
          Improvements: '',
          SubmittedBy: _ui(_P.janeSmith[0], _P.janeSmith[1]),
          SubmittedByEmail: 'jane.smith@example.com',
          AccessLevel: 'Internal',
        },
        {
          Id: 2,
          Title: 'ECH - Master Source',
          UUID: 'uuid-proj-002',
          UmbrellaProgram: 'Digital Transformation',
          LinkedPrograms: 'uuid-prog-001',
          Context: 'Central data repository for enterprise client hierarchy. Single source of truth for client relationship data across business lines.',
          Objectives: 'Establish a golden source for client data, reducing reconciliation efforts by 60%.',
          Scope: 'In Scope',
          ProjectType: 'Data',
          TechProject: '',
          TechPhase: '',
          StartDate: '2025-10-01',
          ExpectedEndDate: '2026-09-30',
          GDPRClassification: 'Non-sensitive Personal Data: Other Information (OPD)',
          BusinessLine: 'GCM',
          Product: 'ECH Platform',
          Sponsor: _ui(_P.carlosDiaz[0], _P.carlosDiaz[1]),
          Stakeholders: _uiArr([_P.jenniferLee, _P.mikeBrown]),
          PMMembers: _uiArr([_P.johnDoe, _P.carlosDiaz]),
          PMMembersEmail: 'john.doe@example.com;carlos.diaz@example.com',
          Status: 'In Progress',
          ProjectManager: _ui(_P.aliceWong[0], _P.aliceWong[1]),
          ProjectManagerEmail: 'alice.wong@example.com',
          Role: 'Leading',
          TargetType: 'Cost Avoidance',
          TargetValue: '1200000',
          TargetValueType: 'EUR',
          TargetScope: 'Global',
          AchievedValue: '',
          AchievedDate: '',
          Validated: 'false',
          NpsScore: '',
          ClientFeedback: '',
          Improvements: '',
          SubmittedBy: _ui(_P.aliceWong[0], _P.aliceWong[1]),
          SubmittedByEmail: 'alice.wong@example.com',
          AccessLevel: 'Internal',
        },
        {
          Id: 3,
          Title: 'Wave - Client Onboarding',
          UUID: 'uuid-proj-003',
          UmbrellaProgram: 'Client Experience',
          LinkedPrograms: 'uuid-prog-002',
          Context: 'Streamlined client onboarding platform replacing the current multi-step manual process with a digital workflow.',
          Objectives: 'Cut onboarding time from 15 days to 5 days and improve client satisfaction scores.',
          Scope: 'In Scope',
          ProjectType: 'Transformation',
          TechProject: '',
          TechPhase: '',
          StartDate: '2025-11-10',
          ExpectedEndDate: '2026-08-15',
          GDPRClassification: 'Contact Information (CPD)',
          BusinessLine: 'TB',
          Product: 'Wave Portal',
          Sponsor: _ui(_P.sarahWilliams[0], _P.sarahWilliams[1]),
          Stakeholders: _uiArr([_P.davidPark, _P.emmaWhite]),
          PMMembers: _uiArr([_P.johnDoe, _P.emmaWhite]),
          PMMembersEmail: 'john.doe@example.com;emma.white@example.com',
          Status: 'In Progress',
          ProjectManager: _ui(_P.carlosDiaz[0], _P.carlosDiaz[1]),
          ProjectManagerEmail: 'carlos.diaz@example.com',
          Role: 'Leading',
          TargetType: 'Client Experience',
          TargetValue: '800000',
          TargetValueType: 'EUR',
          TargetScope: 'EMEA',
          AchievedValue: '',
          AchievedDate: '',
          Validated: 'false',
          NpsScore: '',
          ClientFeedback: '',
          Improvements: '',
          SubmittedBy: _ui(_P.carlosDiaz[0], _P.carlosDiaz[1]),
          SubmittedByEmail: 'carlos.diaz@example.com',
          AccessLevel: 'Internal',
        },
        {
          Id: 4,
          Title: 'Macarron - Risk Dashboard',
          UUID: 'uuid-proj-004',
          UmbrellaProgram: 'Operational Excellence',
          LinkedPrograms: 'uuid-prog-003',
          Context: 'Real-time risk analytics dashboard providing consolidated views across credit, market, and operational risk dimensions.',
          Objectives: 'Deliver daily risk exposure reports in under 2 hours instead of the current 8-hour batch process.',
          Scope: 'In Scope',
          ProjectType: 'Tech',
          TechProject: 'PowerBI',
          TechPhase: 'Discovery',
          StartDate: '2026-02-01',
          ExpectedEndDate: '2026-11-30',
          GDPRClassification: 'Non-sensitive Personal Data: Other Information (OPD)',
          BusinessLine: 'CCCO',
          Product: 'Risk Dashboard',
          Sponsor: _ui(_P.bobJones[0], _P.bobJones[1]),
          Stakeholders: _uiArr([_P.aliceWong, _P.janeSmith]),
          PMMembers: _uiArr([_P.mariaGarcia]),
          PMMembersEmail: 'maria.garcia@example.com',
          Status: 'Pipeline',
          ProjectManager: _ui(_P.mariaGarcia[0], _P.mariaGarcia[1]),
          ProjectManagerEmail: 'maria.garcia@example.com',
          Role: 'Leading',
          TargetType: 'Operational Risk',
          TargetValue: '300000',
          TargetValueType: 'EUR',
          TargetScope: 'Global',
          AchievedValue: '',
          AchievedDate: '',
          Validated: 'false',
          NpsScore: '',
          ClientFeedback: '',
          Improvements: '',
          SubmittedBy: _ui(_P.mariaGarcia[0], _P.mariaGarcia[1]),
          SubmittedByEmail: 'maria.garcia@example.com',
          AccessLevel: 'Confidential',
        },
        {
          Id: 5,
          Title: 'Proxy 1 - Compliance Automation',
          UUID: 'uuid-proj-005',
          UmbrellaProgram: 'Operational Excellence',
          LinkedPrograms: 'uuid-prog-003',
          Context: 'Automated compliance checking framework that monitors regulatory requirements and generates audit-ready reports.',
          Objectives: 'Automate 80% of manual compliance checks and reduce audit preparation time by 50%.',
          Scope: 'In Scope',
          ProjectType: 'Lean',
          TechProject: '',
          TechPhase: '',
          StartDate: '2025-06-01',
          ExpectedEndDate: '2026-01-31',
          GDPRClassification: 'Sensitive Personal Data (SPD)',
          BusinessLine: 'Finance',
          Product: 'Compliance Engine',
          Sponsor: _ui(_P.jenniferLee[0], _P.jenniferLee[1]),
          Stakeholders: _uiArr([_P.mikeBrown, _P.davidPark]),
          PMMembers: _uiArr([_P.sarahWilliams]),
          PMMembersEmail: 'sarah.williams@example.com',
          Status: 'Completed',
          ProjectManager: _ui(_P.sarahWilliams[0], _P.sarahWilliams[1]),
          ProjectManagerEmail: 'sarah.williams@example.com',
          Role: 'Leading',
          TargetType: 'Cost Avoidance',
          TargetValue: '450000',
          TargetValueType: 'EUR',
          TargetScope: 'EMEA',
          AchievedValue: '420000',
          AchievedDate: '2026-01-15',
          Validated: 'true',
          NpsScore: '8',
          ClientFeedback: 'Excellent tool that has significantly streamlined our compliance workflows. The automated checks catch issues we previously missed in manual reviews.',
          Improvements: 'Would benefit from integration with the new regulatory feed API. Also, the report export could support more formats beyond PDF.',
          SubmittedBy: _ui(_P.sarahWilliams[0], _P.sarahWilliams[1]),
          SubmittedByEmail: 'sarah.williams@example.com',
          AccessLevel: 'NoRestriction',
        },
        {
          Id: 6,
          Title: 'Saba - Learning Platform',
          UUID: 'uuid-proj-006',
          UmbrellaProgram: 'Client Experience',
          LinkedPrograms: 'uuid-prog-002',
          Context: 'Corporate learning management system migration to a modern platform with improved content delivery and tracking capabilities.',
          Objectives: 'Migrate all 2000+ courses to the new platform and achieve 90% employee adoption within 6 months.',
          Scope: 'In Scope',
          ProjectType: 'PMO',
          TechProject: '',
          TechPhase: '',
          StartDate: '2025-08-01',
          ExpectedEndDate: '2026-04-30',
          GDPRClassification: 'Non-sensitive Personal Data: Other Information (OPD)',
          BusinessLine: 'HR',
          Product: 'Saba LMS',
          Sponsor: _ui(_P.emmaWhite[0], _P.emmaWhite[1]),
          Stakeholders: _uiArr([_P.sarahWilliams, _P.carlosDiaz]),
          PMMembers: _uiArr([_P.aliceWong]),
          PMMembersEmail: 'alice.wong@example.com',
          Status: 'Delayed',
          ProjectManager: _ui(_P.aliceWong[0], _P.aliceWong[1]),
          ProjectManagerEmail: 'alice.wong@example.com',
          Role: 'Leading',
          TargetType: 'Employee Satisfaction',
          TargetValue: '',
          TargetValueType: '',
          TargetScope: 'Global',
          AchievedValue: '',
          AchievedDate: '',
          Validated: 'false',
          NpsScore: '',
          ClientFeedback: '',
          Improvements: '',
          SubmittedBy: _ui(_P.aliceWong[0], _P.aliceWong[1]),
          SubmittedByEmail: 'alice.wong@example.com',
          AccessLevel: 'Internal',
        },
        {
          Id: 7,
          Title: 'Test 2 - POC Integration',
          UUID: 'uuid-proj-007',
          UmbrellaProgram: 'Digital Transformation',
          LinkedPrograms: 'uuid-prog-001',
          Context: 'Proof of concept for integrating Dataiku machine learning models with existing data pipelines.',
          Objectives: 'Validate the technical feasibility of real-time ML scoring on the transaction processing pipeline.',
          Scope: 'In Scope',
          ProjectType: 'Tech',
          TechProject: 'Dataiku',
          TechPhase: 'Framing',
          StartDate: '2026-01-15',
          ExpectedEndDate: '2026-05-31',
          GDPRClassification: 'Non-sensitive Personal Data: Other Information (OPD)',
          BusinessLine: 'COO',
          Product: 'ML Pipeline',
          Sponsor: _ui(_P.alexMartin[0], _P.alexMartin[1]),
          Stakeholders: _uiArr([_P.janeSmith, _P.mariaGarcia]),
          PMMembers: _uiArr([_P.alexMartin]),
          PMMembersEmail: 'alex.martin@example.com',
          Status: 'Pipeline',
          ProjectManager: _ui(_P.johnDoe[0], _P.johnDoe[1]),
          ProjectManagerEmail: 'john.doe@example.com',
          Role: 'Leading',
          TargetType: 'Revenues',
          TargetValue: '200000',
          TargetValueType: 'EUR',
          TargetScope: 'EMEA',
          AchievedValue: '',
          AchievedDate: '',
          Validated: 'false',
          NpsScore: '',
          ClientFeedback: '',
          Improvements: '',
          SubmittedBy: _ui(_P.johnDoe[0], _P.johnDoe[1]),
          SubmittedByEmail: 'john.doe@example.com',
          AccessLevel: 'Internal',
        },
        {
          Id: 8,
          Title: 'Nexus - ML Pipeline',
          UUID: 'uuid-proj-008',
          UmbrellaProgram: 'Digital Transformation - Wave 2',
          LinkedPrograms: 'uuid-prog-004',
          Context: 'End-to-end machine learning pipeline for real-time credit scoring, integrating Dataiku model registry with the transaction processing API.',
          Objectives: 'Reduce credit decisioning latency from 3 seconds to under 200ms while maintaining model accuracy above 94%.',
          Scope: 'In Scope',
          ProjectType: 'Tech',
          TechProject: 'Dataiku',
          TechPhase: 'Dev',
          StartDate: '2026-01-20',
          ExpectedEndDate: '2026-09-30',
          GDPRClassification: 'Non-sensitive Personal Data: Other Information (OPD)',
          BusinessLine: 'GCM',
          Product: 'Credit Scoring Engine',
          Sponsor: _ui(_P.janeSmith[0], _P.janeSmith[1]),
          Stakeholders: _uiArr([_P.mariaGarcia, _P.carlosDiaz]),
          PMMembers: _uiArr([_P.alexMartin]),
          PMMembersEmail: 'alex.martin@example.com',
          Status: 'In Progress',
          ProjectManager: _ui(_P.alexMartin[0], _P.alexMartin[1]),
          ProjectManagerEmail: 'alex.martin@example.com',
          Role: 'Leading',
          TargetType: 'Revenues',
          TargetValue: '750000',
          TargetValueType: 'EUR',
          TargetScope: 'EMEA',
          AchievedValue: '',
          AchievedDate: '',
          Validated: 'false',
          NpsScore: '',
          ClientFeedback: '',
          Improvements: '',
          SubmittedBy: _ui(_P.alexMartin[0], _P.alexMartin[1]),
          SubmittedByEmail: 'alex.martin@example.com',
          AccessLevel: 'Internal',
        },
        {
          Id: 9,
          Title: 'Atlas - Feature Store',
          UUID: 'uuid-proj-009',
          UmbrellaProgram: 'Digital Transformation - Wave 2',
          LinkedPrograms: 'uuid-prog-004',
          Context: 'Centralised feature store providing curated ML-ready datasets shared across data science teams, eliminating redundant feature engineering efforts.',
          Objectives: 'Enable feature reuse across 5+ models and reduce data preparation time by 60%.',
          Scope: 'In Scope',
          ProjectType: 'Data',
          TechProject: '',
          TechPhase: '',
          StartDate: '2026-02-15',
          ExpectedEndDate: '2026-10-31',
          GDPRClassification: 'Non-sensitive Personal Data: Other Information (OPD)',
          BusinessLine: 'COO',
          Product: 'Feature Store',
          Sponsor: _ui(_P.aliceWong[0], _P.aliceWong[1]),
          Stakeholders: _uiArr([_P.davidPark, _P.jenniferLee]),
          PMMembers: _uiArr([_P.jenniferLee]),
          PMMembersEmail: 'jennifer.lee@example.com',
          Status: 'Pipeline',
          ProjectManager: _ui(_P.jenniferLee[0], _P.jenniferLee[1]),
          ProjectManagerEmail: 'jennifer.lee@example.com',
          Role: 'Leading',
          TargetType: 'Cost Avoidance',
          TargetValue: '300000',
          TargetValueType: 'EUR',
          TargetScope: 'Global',
          AchievedValue: '',
          AchievedDate: '',
          Validated: 'false',
          NpsScore: '',
          ClientFeedback: '',
          Improvements: '',
          SubmittedBy: _ui(_P.jenniferLee[0], _P.jenniferLee[1]),
          SubmittedByEmail: 'jennifer.lee@example.com',
          AccessLevel: 'NoRestriction',
        },
        {
          Id: 10,
          Title: 'Helix - LLM Assistant',
          UUID: 'uuid-proj-010',
          UmbrellaProgram: 'DT - AI Initiative',
          LinkedPrograms: 'uuid-prog-005',
          Context: 'Internal LLM-powered assistant for trading desk analysts, providing real-time summarisation of research notes, earnings transcripts, and regulatory filings.',
          Objectives: 'Reduce analyst document review time by 70% and surface actionable insights within 30 seconds of document ingestion.',
          Scope: 'In Scope',
          ProjectType: 'Tech',
          TechProject: 'LLM',
          TechPhase: 'Framing',
          StartDate: '2026-03-01',
          ExpectedEndDate: '2027-01-31',
          GDPRClassification: 'Contact Information (CPD)',
          BusinessLine: 'GCM',
          Product: 'Helix AI',
          Sponsor: _ui(_P.mariaGarcia[0], _P.mariaGarcia[1]),
          Stakeholders: _uiArr([_P.janeSmith, _P.aliceWong]),
          PMMembers: _uiArr([_P.bobJones]),
          PMMembersEmail: 'bob.jones@example.com',
          Status: 'Pipeline',
          ProjectManager: _ui(_P.bobJones[0], _P.bobJones[1]),
          ProjectManagerEmail: 'bob.jones@example.com',
          Role: 'Leading',
          TargetType: 'User Experience',
          TargetValue: '1000000',
          TargetValueType: 'EUR',
          TargetScope: 'Global',
          AchievedValue: '',
          AchievedDate: '',
          Validated: 'false',
          NpsScore: '',
          ClientFeedback: '',
          Improvements: '',
          SubmittedBy: _ui(_P.bobJones[0], _P.bobJones[1]),
          SubmittedByEmail: 'bob.jones@example.com',
          AccessLevel: 'Confidential',
        },
        {
          Id: 11,
          Title: 'Quantum - Prediction Engine',
          UUID: 'uuid-proj-011',
          UmbrellaProgram: 'DT - AI Initiative',
          LinkedPrograms: 'uuid-prog-005',
          Context: 'Predictive analytics engine using gradient boosting models to forecast client churn, product cross-sell opportunities, and portfolio rebalancing triggers.',
          Objectives: 'Achieve 82%+ churn prediction accuracy and generate actionable signals for the CRM 48 hours ahead of churn events.',
          Scope: 'In Scope',
          ProjectType: 'Tech',
          TechProject: 'AI',
          TechPhase: 'Discovery',
          StartDate: '2026-02-01',
          ExpectedEndDate: '2026-12-31',
          GDPRClassification: 'Sensitive Personal Data (SPD)',
          BusinessLine: 'CCG',
          Product: 'Quantum Analytics',
          Sponsor: _ui(_P.janeSmith[0], _P.janeSmith[1]),
          Stakeholders: _uiArr([_P.emmaWhite, _P.mikeBrown]),
          PMMembers: _uiArr([_P.davidPark]),
          PMMembersEmail: 'david.park@example.com',
          Status: 'Delayed',
          ProjectManager: _ui(_P.davidPark[0], _P.davidPark[1]),
          ProjectManagerEmail: 'david.park@example.com',
          Role: 'Leading',
          TargetType: 'Revenues',
          TargetValue: '2000000',
          TargetValueType: 'EUR',
          TargetScope: 'EMEA',
          AchievedValue: '',
          AchievedDate: '',
          Validated: 'false',
          NpsScore: '',
          ClientFeedback: '',
          Improvements: '',
          SubmittedBy: _ui(_P.davidPark[0], _P.davidPark[1]),
          SubmittedByEmail: 'david.park@example.com',
          AccessLevel: 'Internal',
        },
        {
          Id: 12,
          Title: 'Pulse - Mobile App',
          UUID: 'uuid-proj-012',
          UmbrellaProgram: 'CX - Self-Service',
          LinkedPrograms: 'uuid-prog-006',
          Context: 'Native mobile application for retail clients providing account overview, transaction history, and self-service request management with biometric authentication.',
          Objectives: 'Launch iOS and Android apps to 50,000 retail clients with a 4.2+ app store rating within 3 months of go-live.',
          Scope: 'In Scope',
          ProjectType: 'Tech',
          TechProject: 'LightDev',
          TechPhase: 'Dev',
          StartDate: '2025-12-01',
          ExpectedEndDate: '2026-07-31',
          GDPRClassification: 'Contact Information (CPD)',
          BusinessLine: 'TB',
          Product: 'Pulse Mobile',
          Sponsor: _ui(_P.sarahWilliams[0], _P.sarahWilliams[1]),
          Stakeholders: _uiArr([_P.emmaWhite, _P.alexMartin]),
          PMMembers: _uiArr([_P.carlosDiaz]),
          PMMembersEmail: 'carlos.diaz@example.com',
          Status: 'In Progress',
          ProjectManager: _ui(_P.carlosDiaz[0], _P.carlosDiaz[1]),
          ProjectManagerEmail: 'carlos.diaz@example.com',
          Role: 'Leading',
          TargetType: 'Client Experience',
          TargetValue: '600000',
          TargetValueType: 'EUR',
          TargetScope: 'EMEA',
          AchievedValue: '',
          AchievedDate: '',
          Validated: 'false',
          NpsScore: '',
          ClientFeedback: '',
          Improvements: '',
          SubmittedBy: _ui(_P.carlosDiaz[0], _P.carlosDiaz[1]),
          SubmittedByEmail: 'carlos.diaz@example.com',
          AccessLevel: 'Internal',
        },
        {
          Id: 13,
          Title: 'Forge - ETL Framework',
          UUID: 'uuid-proj-013',
          UmbrellaProgram: 'OpEx - Process Automation',
          LinkedPrograms: 'uuid-prog-007',
          Context: 'Unified ETL framework standardising data extraction, transformation, and loading processes across 20+ source systems, replacing bespoke scripts with a governed pipeline platform.',
          Objectives: 'Reduce pipeline maintenance effort by 50% and achieve full lineage traceability across all data flows.',
          Scope: 'In Scope',
          ProjectType: 'Data',
          TechProject: '',
          TechPhase: '',
          StartDate: '2025-10-15',
          ExpectedEndDate: '2026-06-30',
          GDPRClassification: 'Non-sensitive Personal Data: Other Information (OPD)',
          BusinessLine: 'Finance',
          Product: 'Forge Pipeline',
          Sponsor: _ui(_P.mikeBrown[0], _P.mikeBrown[1]),
          Stakeholders: _uiArr([_P.jenniferLee, _P.alexMartin]),
          PMMembers: _uiArr([_P.sarahWilliams]),
          PMMembersEmail: 'sarah.williams@example.com',
          Status: 'In Progress',
          ProjectManager: _ui(_P.sarahWilliams[0], _P.sarahWilliams[1]),
          ProjectManagerEmail: 'sarah.williams@example.com',
          Role: 'Leading',
          TargetType: 'Cost Avoidance',
          TargetValue: '400000',
          TargetValueType: 'EUR',
          TargetScope: 'Global',
          AchievedValue: '',
          AchievedDate: '',
          Validated: 'false',
          NpsScore: '',
          ClientFeedback: '',
          Improvements: '',
          SubmittedBy: _ui(_P.sarahWilliams[0], _P.sarahWilliams[1]),
          SubmittedByEmail: 'sarah.williams@example.com',
          AccessLevel: 'NoRestriction',
        },
        {
          Id: 14,
          Title: 'Shield - Audit Trail',
          UUID: 'uuid-proj-014',
          UmbrellaProgram: 'OpEx - Process Automation',
          LinkedPrograms: 'uuid-prog-007',
          Context: 'Immutable audit trail system capturing all user actions, data changes, and system events across regulated workflows to support internal audit and regulatory reporting.',
          Objectives: 'Achieve full audit coverage of 12 regulated processes and reduce audit evidence preparation time from 2 weeks to 2 days.',
          Scope: 'In Scope',
          ProjectType: 'Lean',
          TechProject: '',
          TechPhase: '',
          StartDate: '2026-01-10',
          ExpectedEndDate: '2026-08-31',
          GDPRClassification: 'Sensitive Personal Data (SPD)',
          BusinessLine: 'CCCO',
          Product: 'Shield Audit',
          Sponsor: _ui(_P.jenniferLee[0], _P.jenniferLee[1]),
          Stakeholders: _uiArr([_P.davidPark, _P.mikeBrown]),
          PMMembers: _uiArr([_P.aliceWong]),
          PMMembersEmail: 'alice.wong@example.com',
          Status: 'Pipeline',
          ProjectManager: _ui(_P.aliceWong[0], _P.aliceWong[1]),
          ProjectManagerEmail: 'alice.wong@example.com',
          Role: 'Leading',
          TargetType: 'Operational Risk',
          TargetValue: '250000',
          TargetValueType: 'EUR',
          TargetScope: 'Global',
          AchievedValue: '',
          AchievedDate: '',
          Validated: 'false',
          NpsScore: '',
          ClientFeedback: '',
          Improvements: '',
          SubmittedBy: _ui(_P.aliceWong[0], _P.aliceWong[1]),
          SubmittedByEmail: 'alice.wong@example.com',
          AccessLevel: 'Internal',
        },
        {
          Id: 15,
          Title: 'Titan - Cloud Platform',
          UUID: 'uuid-proj-015',
          UmbrellaProgram: 'DT - Cloud Migration',
          LinkedPrograms: 'uuid-prog-008',
          Context: 'Migration of the core intranet and document management workloads from on-premises SharePoint 2016 to SharePoint Online, enabling cloud-native collaboration and search.',
          Objectives: 'Complete migration of 400,000 documents across 80 site collections with zero data loss and less than 4 hours of downtime.',
          Scope: 'In Scope',
          ProjectType: 'Tech',
          TechProject: 'SharePoint',
          TechPhase: 'Business Case',
          StartDate: '2026-04-01',
          ExpectedEndDate: '2027-03-31',
          GDPRClassification: 'Contact Information (CPD)',
          BusinessLine: 'COO',
          Product: 'SharePoint Online',
          Sponsor: _ui(_P.mariaGarcia[0], _P.mariaGarcia[1]),
          Stakeholders: _uiArr([_P.janeSmith, _P.emmaWhite]),
          PMMembers: _uiArr([_P.johnDoe]),
          PMMembersEmail: 'john.doe@example.com',
          Status: 'Pipeline',
          ProjectManager: _ui(_P.johnDoe[0], _P.johnDoe[1]),
          ProjectManagerEmail: 'john.doe@example.com',
          Role: 'Leading',
          TargetType: 'Cost Avoidance',
          TargetValue: '500000',
          TargetValueType: 'EUR',
          TargetScope: 'Global',
          AchievedValue: '',
          AchievedDate: '',
          Validated: 'false',
          NpsScore: '',
          ClientFeedback: '',
          Improvements: '',
          SubmittedBy: _ui(_P.johnDoe[0], _P.johnDoe[1]),
          SubmittedByEmail: 'john.doe@example.com',
          AccessLevel: 'Internal',
        },
      ],
    },

    Programs: {
      nextId: 9,
      fields: [
        { Title: 'Title', InternalName: 'Title', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: true },
        { Title: 'UUID', InternalName: 'UUID', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: true },
        { Title: 'Context', InternalName: 'Context', TypeAsString: 'Note', FieldTypeKind: 3, Indexed: false },
        { Title: 'ProgramSponsor', InternalName: 'ProgramSponsor', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: false },
        { Title: 'Stakeholders', InternalName: 'Stakeholders', TypeAsString: 'Note', FieldTypeKind: 3, Indexed: false },
        { Title: 'UmbrellaProgram', InternalName: 'UmbrellaProgram', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: false },
        { Title: 'LinkedPrograms', InternalName: 'LinkedPrograms', TypeAsString: 'Note', FieldTypeKind: 3, Indexed: false },
        { Title: 'SubmittedBy', InternalName: 'SubmittedBy', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: false },
        { Title: 'SubmittedByEmail', InternalName: 'SubmittedByEmail', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: true },
      ],
      items: [
        {
          Id: 1,
          Title: 'Digital Transformation',
          UUID: 'uuid-prog-001',
          ProgramSponsor: _ui(_P.mariaGarcia[0], _P.mariaGarcia[1]),
          Stakeholders: _uiArr([_P.janeSmith, _P.aliceWong, _P.johnDoe]),
          Context: 'Strategic initiative to modernize core banking systems and migrate legacy infrastructure to cloud-native platforms, enabling faster time-to-market for digital products.',
          UmbrellaProgram: '',
          LinkedPrograms: '',
          SubmittedBy: _ui(_P.johnDoe[0], _P.johnDoe[1]),
          SubmittedByEmail: 'john.doe@example.com',
        },
        {
          Id: 2,
          Title: 'Client Experience',
          UUID: 'uuid-prog-002',
          ProgramSponsor: _ui(_P.sarahWilliams[0], _P.sarahWilliams[1]),
          Stakeholders: _uiArr([_P.carlosDiaz, _P.emmaWhite]),
          Context: 'Cross-functional program focused on improving client-facing touchpoints, from onboarding to ongoing service delivery, to increase NPS and reduce churn.',
          UmbrellaProgram: '',
          LinkedPrograms: '',
          SubmittedBy: _ui(_P.johnDoe[0], _P.johnDoe[1]),
          SubmittedByEmail: 'john.doe@example.com',
        },
        {
          Id: 3,
          Title: 'Operational Excellence',
          UUID: 'uuid-prog-003',
          ProgramSponsor: _ui(_P.bobJones[0], _P.bobJones[1]),
          Stakeholders: _uiArr([_P.mariaGarcia, _P.sarahWilliams, _P.jenniferLee]),
          Context: 'Continuous improvement program targeting operational efficiency through process automation, waste reduction, and compliance streamlining across back-office functions.',
          UmbrellaProgram: '',
          LinkedPrograms: '',
          SubmittedBy: _ui(_P.johnDoe[0], _P.johnDoe[1]),
          SubmittedByEmail: 'john.doe@example.com',
        },
        {
          Id: 4,
          Title: 'Digital Transformation - Wave 2',
          UUID: 'uuid-prog-004',
          ProgramSponsor: _ui(_P.janeSmith[0], _P.janeSmith[1]),
          Stakeholders: _uiArr([_P.aliceWong, _P.bobJones]),
          Context: 'Second wave of the Digital Transformation program, focused on AI and automation initiatives to complement the first-wave SharePoint and Data projects.',
          UmbrellaProgram: 'Digital Transformation',
          LinkedPrograms: 'uuid-prog-001',
          SubmittedBy: _ui(_P.johnDoe[0], _P.johnDoe[1]),
          SubmittedByEmail: 'john.doe@example.com',
        },
        {
          Id: 5,
          Title: 'DT - AI Initiative',
          UUID: 'uuid-prog-005',
          ProgramSponsor: _ui(_P.aliceWong[0], _P.aliceWong[1]),
          Stakeholders: _uiArr([_P.davidPark, _P.emmaWhite]),
          Context: 'AI-focused sub-initiative under Wave 2, exploring large language model integration and intelligent automation for trading and compliance use cases.',
          UmbrellaProgram: 'Digital Transformation - Wave 2',
          LinkedPrograms: 'uuid-prog-004',
          SubmittedBy: _ui(_P.johnDoe[0], _P.johnDoe[1]),
          SubmittedByEmail: 'john.doe@example.com',
        },
        {
          Id: 6,
          Title: 'CX - Self-Service',
          UUID: 'uuid-prog-006',
          ProgramSponsor: _ui(_P.carlosDiaz[0], _P.carlosDiaz[1]),
          Stakeholders: _uiArr([_P.jenniferLee, _P.mikeBrown]),
          Context: 'Program to expand self-service capabilities across the client portal, mobile applications, and automated support channels.',
          UmbrellaProgram: 'Client Experience',
          LinkedPrograms: 'uuid-prog-002',
          SubmittedBy: _ui(_P.johnDoe[0], _P.johnDoe[1]),
          SubmittedByEmail: 'john.doe@example.com',
        },
        {
          Id: 7,
          Title: 'OpEx - Process Automation',
          UUID: 'uuid-prog-007',
          ProgramSponsor: _ui(_P.sarahWilliams[0], _P.sarahWilliams[1]),
          Stakeholders: _uiArr([_P.alexMartin, _P.bobJones]),
          Context: 'Structured automation workstream under Operational Excellence, targeting high-volume back-office processes for RPA and workflow automation candidates.',
          UmbrellaProgram: 'Operational Excellence',
          LinkedPrograms: 'uuid-prog-003',
          SubmittedBy: _ui(_P.johnDoe[0], _P.johnDoe[1]),
          SubmittedByEmail: 'john.doe@example.com',
        },
        {
          Id: 8,
          Title: 'DT - Cloud Migration',
          UUID: 'uuid-prog-008',
          ProgramSponsor: _ui(_P.bobJones[0], _P.bobJones[1]),
          Stakeholders: _uiArr([_P.janeSmith, _P.carlosDiaz]),
          Context: 'Cloud-first infrastructure migration program to move on-premises workloads to hybrid cloud, enabling scalability and cost optimization for core banking platforms.',
          UmbrellaProgram: 'Digital Transformation',
          LinkedPrograms: 'uuid-prog-001',
          SubmittedBy: _ui(_P.johnDoe[0], _P.johnDoe[1]),
          SubmittedByEmail: 'john.doe@example.com',
        },
      ],
    },

    ProjectUpdates: {
      nextId: 5,
      fields: [
        { Title: 'Title', InternalName: 'Title', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: true },
        { Title: 'UUID', InternalName: 'UUID', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: true },
        { Title: 'ProjectUUID', InternalName: 'ProjectUUID', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: true },
        { Title: 'Achievements', InternalName: 'Achievements', TypeAsString: 'Note', FieldTypeKind: 3, Indexed: false },
        { Title: 'Roadblocks', InternalName: 'Roadblocks', TypeAsString: 'Note', FieldTypeKind: 3, Indexed: false },
        { Title: 'ExpectedEndDate', InternalName: 'ExpectedEndDate', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: false },
        { Title: 'NextSteps', InternalName: 'NextSteps', TypeAsString: 'Note', FieldTypeKind: 3, Indexed: false },
        { Title: 'UpdateDate', InternalName: 'UpdateDate', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: false },
        { Title: 'SubmittedBy', InternalName: 'SubmittedBy', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: false },
        { Title: 'SubmittedByEmail', InternalName: 'SubmittedByEmail', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: true },
      ],
      items: [
        {
          Id: 1,
          Title: 'IB4F - IB Portal ECM - 2026-02-15',
          UUID: 'uuid-upd-001',
          ProjectUUID: 'uuid-proj-001',
          Achievements: 'Completed Sprint 3 deliverables including document upload workflow and metadata tagging. All acceptance criteria met.',
          Roadblocks: 'Integration with legacy DMS delayed due to API compatibility issues. Workaround identified using middleware adapter.',
          ExpectedEndDate: '2026-06-30',
          NextSteps: 'Begin Sprint 4 focusing on search functionality and permission model. Schedule architecture review with security team.',
          UpdateDate: '2026-02-15',
          SubmittedBy: _ui(_P.janeSmith[0], _P.janeSmith[1]),
          SubmittedByEmail: 'jane.smith@example.com',
        },
        {
          Id: 2,
          Title: 'IB4F - IB Portal ECM - 2025-11-05',
          UUID: 'uuid-upd-002',
          ProjectUUID: 'uuid-proj-001',
          Achievements: 'Project kickoff completed. Team onboarded, development environment provisioned, initial backlog groomed.',
          Roadblocks: 'Procurement delay on SharePoint licenses. Using dev tenant in the meantime.',
          ExpectedEndDate: '2026-06-30',
          NextSteps: 'Start Sprint 1 with core document library setup and basic upload functionality.',
          UpdateDate: '2025-11-05',
          SubmittedBy: _ui(_P.janeSmith[0], _P.janeSmith[1]),
          SubmittedByEmail: 'jane.smith@example.com',
        },
        {
          Id: 3,
          Title: 'ECH - Master Source - 2026-01-20',
          UUID: 'uuid-upd-003',
          ProjectUUID: 'uuid-proj-002',
          Achievements: 'Data model finalized after stakeholder workshops. Entity relationships mapped across 12 source systems.',
          Roadblocks: 'Data quality issues identified in 3 legacy sources. Cleansing effort estimated at 4 weeks.',
          ExpectedEndDate: '2026-09-30',
          NextSteps: 'Initiate data cleansing workstream. Begin ETL pipeline development for priority sources.',
          UpdateDate: '2026-01-20',
          SubmittedBy: _ui(_P.aliceWong[0], _P.aliceWong[1]),
          SubmittedByEmail: 'alice.wong@example.com',
        },
        {
          Id: 4,
          Title: 'Wave - Client Onboarding - 2026-02-01',
          UUID: 'uuid-upd-004',
          ProjectUUID: 'uuid-proj-003',
          Achievements: 'Phase 1 digital forms rolled out to pilot group. 15 clients onboarded through new workflow with positive feedback.',
          Roadblocks: 'KYC verification step requires manual intervention for non-standard entity types. Automation scope being reassessed.',
          ExpectedEndDate: '2026-08-15',
          NextSteps: 'Expand pilot to full retail segment. Begin Phase 2 development for institutional client onboarding.',
          UpdateDate: '2026-02-01',
          SubmittedBy: _ui(_P.carlosDiaz[0], _P.carlosDiaz[1]),
          SubmittedByEmail: 'carlos.diaz@example.com',
        },
      ],
    },

    Proposals: {
      nextId: 6,
      fields: [
        { Title: 'Title', InternalName: 'Title', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: true },
        { Title: 'UUID', InternalName: 'UUID', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: true },
        { Title: 'Context', InternalName: 'Context', TypeAsString: 'Note', FieldTypeKind: 3, Indexed: false },
        { Title: 'ProjectType', InternalName: 'ProjectType', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: true },
        { Title: 'BusinessLine', InternalName: 'BusinessLine', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: false },
        { Title: 'Sponsor', InternalName: 'Sponsor', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: false },
        { Title: 'Status', InternalName: 'Status', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: true },
        { Title: 'SubmittedBy', InternalName: 'SubmittedBy', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: false },
        { Title: 'SubmittedByEmail', InternalName: 'SubmittedByEmail', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: true },
      ],
      items: [
        {
          Id: 1,
          Title: 'API Gateway Modernization',
          UUID: 'uuid-prop-001',
          Context: 'Migrate legacy SOAP-based API layer to RESTful microservices for improved scalability and developer experience.',
          ProjectType: 'Tech',
          BusinessLine: 'TB',
          Sponsor: _ui(_P.aliceWong[0], _P.aliceWong[1]),
          Status: 'Pipeline',
          SubmittedBy: _ui(_P.johnDoe[0], _P.johnDoe[1]),
          SubmittedByEmail: 'john.doe@example.com',
        },
        {
          Id: 2,
          Title: 'Employee Wellbeing Dashboard',
          UUID: 'uuid-prop-002',
          Context: 'Build a centralized dashboard to track and visualize employee wellbeing metrics across business lines.',
          ProjectType: 'Data',
          BusinessLine: 'HR',
          Sponsor: _ui(_P.mariaGarcia[0], _P.mariaGarcia[1]),
          Status: 'Pipeline',
          SubmittedBy: _ui(_P.johnDoe[0], _P.johnDoe[1]),
          SubmittedByEmail: 'john.doe@example.com',
        },
        {
          Id: 3,
          Title: 'Trade Floor Workflow Automation',
          UUID: 'uuid-prop-003',
          Context: 'Automate manual trade confirmation and reconciliation workflows to reduce operational risk and processing time.',
          ProjectType: 'Lean',
          BusinessLine: 'GCM',
          Sponsor: _ui(_P.carlosDiaz[0], _P.carlosDiaz[1]),
          Status: 'Pipeline',
          SubmittedBy: _ui(_P.johnDoe[0], _P.johnDoe[1]),
          SubmittedByEmail: 'john.doe@example.com',
        },
        {
          Id: 4,
          Title: 'ESG Reporting Framework',
          UUID: 'uuid-prop-004',
          Context: 'Establish a standardized framework for collecting, validating, and reporting ESG data across all business units.',
          ProjectType: 'Consultancy',
          BusinessLine: 'ESG',
          Sponsor: _ui(_P.sarahWilliams[0], _P.sarahWilliams[1]),
          Status: 'Pipeline',
          SubmittedBy: _ui(_P.johnDoe[0], _P.johnDoe[1]),
          SubmittedByEmail: 'john.doe@example.com',
        },
        {
          Id: 5,
          Title: 'Client Portal Redesign',
          UUID: 'uuid-prop-005',
          Context: 'Redesign the external client portal with modern UX patterns to improve self-service capabilities and reduce support tickets.',
          ProjectType: 'Transformation',
          BusinessLine: 'CCG',
          Sponsor: _ui(_P.janeSmith[0], _P.janeSmith[1]),
          Status: 'On Hold',
          SubmittedBy: _ui(_P.johnDoe[0], _P.johnDoe[1]),
          SubmittedByEmail: 'john.doe@example.com',
        },
      ],
    },

    Definitions: {
      nextId: 51,
      fields: [
        { Title: 'Title', InternalName: 'Title', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: true },
        { Title: 'Value', InternalName: 'Value', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: true },
        { Title: 'IsActive', InternalName: 'IsActive', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: false },
      ],
      items: [
        // ProjectTypes (IDs 1-6)
        { Id: 1, Title: 'ProjectTypes', Value: 'Consultancy', IsActive: 'true' },
        { Id: 2, Title: 'ProjectTypes', Value: 'Transformation', IsActive: 'true' },
        { Id: 3, Title: 'ProjectTypes', Value: 'Lean', IsActive: 'true' },
        { Id: 4, Title: 'ProjectTypes', Value: 'PMO', IsActive: 'true' },
        { Id: 5, Title: 'ProjectTypes', Value: 'Tech', IsActive: 'true' },
        { Id: 6, Title: 'ProjectTypes', Value: 'Data', IsActive: 'true' },
        // TechProjects (IDs 7-14)
        { Id: 7, Title: 'TechProjects', Value: 'SharePoint', IsActive: 'true' },
        { Id: 8, Title: 'TechProjects', Value: 'PowerBI', IsActive: 'true' },
        { Id: 9, Title: 'TechProjects', Value: 'Dataiku', IsActive: 'true' },
        { Id: 10, Title: 'TechProjects', Value: 'LightDev', IsActive: 'true' },
        { Id: 11, Title: 'TechProjects', Value: 'Automation', IsActive: 'true' },
        { Id: 12, Title: 'TechProjects', Value: 'AI', IsActive: 'true' },
        { Id: 13, Title: 'TechProjects', Value: 'LLM', IsActive: 'true' },
        { Id: 14, Title: 'TechProjects', Value: 'Centric/NOA', IsActive: 'true' },
        // TechPhases (IDs 15-20)
        { Id: 15, Title: 'TechPhases', Value: 'Discovery', IsActive: 'true' },
        { Id: 16, Title: 'TechPhases', Value: 'Framing', IsActive: 'true' },
        { Id: 17, Title: 'TechPhases', Value: 'Business Case', IsActive: 'true' },
        { Id: 18, Title: 'TechPhases', Value: 'Dev', IsActive: 'true' },
        { Id: 19, Title: 'TechPhases', Value: 'Live', IsActive: 'true' },
        { Id: 20, Title: 'TechPhases', Value: 'CM', IsActive: 'true' },
        // ProjectStatuses (IDs 21-26)
        { Id: 21, Title: 'ProjectStatuses', Value: 'Pipeline', IsActive: 'true' },
        { Id: 22, Title: 'ProjectStatuses', Value: 'On Hold', IsActive: 'true' },
        { Id: 23, Title: 'ProjectStatuses', Value: 'In Progress', IsActive: 'true' },
        { Id: 24, Title: 'ProjectStatuses', Value: 'Completed', IsActive: 'true' },
        { Id: 25, Title: 'ProjectStatuses', Value: 'Stopped', IsActive: 'true' },
        { Id: 26, Title: 'ProjectStatuses', Value: 'Delayed', IsActive: 'true' },
        // BusinessLines (IDs 27-35)
        { Id: 27, Title: 'BusinessLines', Value: 'CCG', IsActive: 'true' },
        { Id: 28, Title: 'BusinessLines', Value: 'GCM', IsActive: 'true' },
        { Id: 29, Title: 'BusinessLines', Value: 'TB', IsActive: 'true' },
        { Id: 30, Title: 'BusinessLines', Value: 'CCCO', IsActive: 'true' },
        { Id: 31, Title: 'BusinessLines', Value: 'ESG', IsActive: 'true' },
        { Id: 32, Title: 'BusinessLines', Value: 'Finance', IsActive: 'true' },
        { Id: 33, Title: 'BusinessLines', Value: 'HR', IsActive: 'true' },
        { Id: 34, Title: 'BusinessLines', Value: 'COO', IsActive: 'true' },
        { Id: 35, Title: 'BusinessLines', Value: 'Transversal', IsActive: 'true' },
        // TargetTypes (IDs 36-42)
        { Id: 36, Title: 'TargetTypes', Value: 'User Experience', IsActive: 'true' },
        { Id: 37, Title: 'TargetTypes', Value: 'Client Experience', IsActive: 'true' },
        { Id: 38, Title: 'TargetTypes', Value: 'Revenues', IsActive: 'true' },
        { Id: 39, Title: 'TargetTypes', Value: 'Cost Avoidance', IsActive: 'true' },
        { Id: 40, Title: 'TargetTypes', Value: 'RWA', IsActive: 'true' },
        { Id: 41, Title: 'TargetTypes', Value: 'Operational Risk', IsActive: 'true' },
        { Id: 42, Title: 'TargetTypes', Value: 'Employee Satisfaction', IsActive: 'true' },
        // TargetValueTypes (IDs 43-46)
        { Id: 43, Title: 'TargetValueTypes', Value: 'EUR', IsActive: 'true' },
        { Id: 44, Title: 'TargetValueTypes', Value: 'USD', IsActive: 'true' },
        { Id: 45, Title: 'TargetValueTypes', Value: 'GBP', IsActive: 'true' },
        { Id: 46, Title: 'TargetValueTypes', Value: 'FTE', IsActive: 'true' },
        // PMScope (IDs 47-50)
        { Id: 47, Title: 'PMScope', Value: 'P4P', IsActive: 'true' },
        { Id: 48, Title: 'PMScope', Value: 'P4P Transversalities', IsActive: 'true' },
        { Id: 49, Title: 'PMScope', Value: 'We Motion', IsActive: 'true' },
        { Id: 50, Title: 'PMScope', Value: 'GB&FIC PT', IsActive: 'true' },
      ],
    },

    UserRoles: {
      nextId: 4,
      fields: [
        { Title: 'Title', InternalName: 'Title', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: true },
        { Title: 'Roles', InternalName: 'Roles', TypeAsString: 'Note', FieldTypeKind: 3, Indexed: false },
      ],
      items: [
        { Id: 1, Title: 'john.doe@example.com', Roles: '["admin","project_manager"]' },
        { Id: 2, Title: 'jane.smith@example.com', Roles: '["project_manager"]' },
        { Id: 3, Title: 'bob.jones@example.com', Roles: '["collaborator"]' },
      ],
    },

    ProjectAccess: {
      nextId: 3,
      fields: [
        { Title: 'Title', InternalName: 'Title', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: true },
        { Title: 'ProjectUUID', InternalName: 'ProjectUUID', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: true },
        { Title: 'UserEmail', InternalName: 'UserEmail', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: true },
        { Title: 'UserDisplayName', InternalName: 'UserDisplayName', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: false },
        { Title: 'AccessType', InternalName: 'AccessType', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: true },
        { Title: 'GrantedBy', InternalName: 'GrantedBy', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: false },
        { Title: 'GrantedByEmail', InternalName: 'GrantedByEmail', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: true },
      ],
      items: [
        {
          Id: 1,
          Title: 'uuid-proj-004_maria.garcia@example.com',
          ProjectUUID: 'uuid-proj-004',
          UserEmail: 'maria.garcia@example.com',
          UserDisplayName: 'Maria Garcia',
          AccessType: 'Contributing',
          GrantedBy: _ui(_P.johnDoe[0], _P.johnDoe[1]),
          GrantedByEmail: 'john.doe@example.com',
        },
        {
          Id: 2,
          Title: 'uuid-proj-004_bob.jones@example.com',
          ProjectUUID: 'uuid-proj-004',
          UserEmail: 'bob.jones@example.com',
          UserDisplayName: 'Bob Jones',
          AccessType: 'Read',
          GrantedBy: _ui(_P.johnDoe[0], _P.johnDoe[1]),
          GrantedByEmail: 'john.doe@example.com',
        },
      ],
    },
    Allocations: {
      nextId: 6,
      fields: [
        { Title: 'Title', InternalName: 'Title', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: true },
        { Title: 'ProjectUUID', InternalName: 'ProjectUUID', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: true },
        { Title: 'UserEmail', InternalName: 'UserEmail', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: true },
        { Title: 'UserDisplayName', InternalName: 'UserDisplayName', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: false },
        { Title: 'AllocationPercent', InternalName: 'AllocationPercent', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: false },
        { Title: 'UpdatedBy', InternalName: 'UpdatedBy', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: false },
        { Title: 'UpdatedByEmail', InternalName: 'UpdatedByEmail', TypeAsString: 'Text', FieldTypeKind: 2, Indexed: true },
      ],
      items: [
        {
          Id: 1,
          Title: 'uuid-proj-001_jane.smith@example.com',
          ProjectUUID: 'uuid-proj-001',
          UserEmail: 'jane.smith@example.com',
          UserDisplayName: 'Jane Smith',
          AllocationPercent: '0.4',
          UpdatedBy: _ui(_P.janeSmith[0], _P.janeSmith[1]),
          UpdatedByEmail: 'jane.smith@example.com',
        },
        {
          Id: 2,
          Title: 'uuid-proj-001_john.doe@example.com',
          ProjectUUID: 'uuid-proj-001',
          UserEmail: 'john.doe@example.com',
          UserDisplayName: 'John Doe',
          AllocationPercent: '0.2',
          UpdatedBy: _ui(_P.johnDoe[0], _P.johnDoe[1]),
          UpdatedByEmail: 'john.doe@example.com',
        },
        {
          Id: 3,
          Title: 'uuid-proj-002_alice.wong@example.com',
          ProjectUUID: 'uuid-proj-002',
          UserEmail: 'alice.wong@example.com',
          UserDisplayName: 'Alice Wong',
          AllocationPercent: '0.5',
          UpdatedBy: _ui(_P.aliceWong[0], _P.aliceWong[1]),
          UpdatedByEmail: 'alice.wong@example.com',
        },
        {
          Id: 4,
          Title: 'uuid-proj-002_john.doe@example.com',
          ProjectUUID: 'uuid-proj-002',
          UserEmail: 'john.doe@example.com',
          UserDisplayName: 'John Doe',
          AllocationPercent: '0.15',
          UpdatedBy: _ui(_P.johnDoe[0], _P.johnDoe[1]),
          UpdatedByEmail: 'john.doe@example.com',
        },
        {
          Id: 5,
          Title: 'uuid-proj-007_john.doe@example.com',
          ProjectUUID: 'uuid-proj-007',
          UserEmail: 'john.doe@example.com',
          UserDisplayName: 'John Doe',
          AllocationPercent: '0.25',
          UpdatedBy: _ui(_P.johnDoe[0], _P.johnDoe[1]),
          UpdatedByEmail: 'john.doe@example.com',
        },
      ],
    },
  },
};
